project:
  type: website
  title: "Computational Imaging"
  output-dir: ../_site

website:
  page-footer:
    center: "Copyright © 2026 University of Geneva"
    
  navbar:
    search: true
    right:
      - text: Language
        icon: globe
        menu:
          - text: "English"
            href: index.html
          - text: "French"
            href: fr/index.html

  sidebar:
    style: docked
    search: true
    contents:
      - section: "Course"
        contents:
          - section: "Introduction"
            contents:
              - text: "Details"
                href: ch1.qmd
              - text: "Review"
                href: ch1r.qmd
              - text: "Quiz"
                href: ch1q.qmd
          - section: "Human Visual System"
            contents:
              - text: "Details"
                href: ch2.qmd
              - text: "Review"
                href: ch2r.qmd
              - text: "Quiz"
                href: ch2q.qmd
          - section: "Computational Photography"
            contents:
              - text: "Details"
                href: ch3.qmd
              - text: "Review"
                href: ch3r.qmd
              - text: "Quiz"
                href: ch3q.qmd
          - section: "Medical Imaging"
            contents:
              - text: "Details"
                href: ch4.qmd
              - text: "Review"
                href: ch4r.qmd
              - text: "Quiz"
                href: ch4q.qmd

format:
  html:
    theme:
      dark: ../macchiato.scss
      light: ../latte.scss
    toc: true
    embed-resources: true
