import numpy as np
import os
from skimage.io import imread

def genDepthSequence(path: str, canonicalName: str, frames: int, format: str) -> np.ndarray:
    """
    Reads depth-map images from a specified path and returns an image sequence.

    The function reads depth-maps from a directory. The combined sequence is useful when processing images to generate a refocused video (see script 'demoSelectiveRefocusVideo.m').

    Parameters
    ----------
    path : str
        Full file system path to folder containing depthmap images.
    canonicalName : str
        Common part of file name.
    frames : int
        Total number of frames to be read.
    format : str
        Image file format, e.g., "png", "jpg".

    Returns
    -------
    np.ndarray
        4D matrix of depthmap images (Width x Height x Color Channels x Number of Frames).

    Notes
    -----
    The file naming is aligned with the depthmap generated by the depthmap generation function in this package.
    Example:
        Filename      = depthMap_0.png
        canonicalName = "depthMap_"
    """
    # Get dimensions of first depthmap to initialize the output matrix
    dim = imread(os.path.join(path, canonicalName + "0." + format)).shape
    # Define Matrix to Store ImSequence
    imSequence = np.zeros((dim[0], dim[1], frames), dtype=np.uint8)
    
    # Read Images
    for i in range(frames):
        sFrame = str(i)
        
        # Set File Path
        fullURI = os.path.join(path, canonicalName + sFrame + "." + format)
        
        # Read Images
        imSequence[:,:,i] = imread(fullURI)
    return imSequence
