project:
  type: website
  title: "Computational Imaging"
  output-dir: ../_site/fr

website:
  page-footer:
    center: "Copyright © 2026 University of Geneva"
    
  navbar:
    search: true
    right:
      - text: Langue
        icon: globe
        menu:
          - text: "Anglais"
            href: ../index.html
          - text: "Français"
            href: index.html

  sidebar:
    search: true
    contents:
      - section: "Cours"
        contents:
          - section: "Introduction"
            contents:
              - text: "Détails"
                href: ch1.qmd
              - text: "Synthèse"
                href: ch1r.qmd
              - text: "Quiz"
                href: ch1q.qmd
          - section: "Système visuel humain"
            contents:
              - text: "Détails"
                href: ch2.qmd
              - text: "Synthèse"
                href: ch2r.qmd
              - text: "Quiz"
                href: ch2q.qmd
          - section: "Photographie computationnelle"
            contents:
              - text: "Détails"
                href: ch3.qmd
              - text: "Synthèse"
                href: ch3r.qmd
              - text: "Quiz"
                href: ch3q.qmd
          - section: "Imagerie médicale"
            contents:
              - text: "Détails"
                href: ch4.qmd
              - text: "Synthèse"
                href: ch4r.qmd
              - text: "Quiz"
                href: ch4q.qmd
          - section: "Microscopes"
            contents:
              - text: "Détails"
                href: ch5.qmd
              - text: "Synthèse"
                href: ch5r.qmd
              - text: "Quiz"
                href: ch5q.qmd
          - section: "Nanoscale imaging"
            contents:
              - text: "Détails"
                href: ch6.qmd
              - text: "Synthèse"
                href: ch6r.qmd
              - text: "Quiz"
                href: ch6q.qmd
      - section: "Examen"
        contents:
          - text: "Détails"
            href: exam_answers.qmd
          - text: "Synthèse"
            href: exam_syntheses.qmd
          - text: "Quiz"
            href: exam_quiz.qmd

format:
  html:
    theme:
      dark: ../macchiato.scss
      light: ../latte.scss
    toc: true
    embed-resources: true
    page-layout: full
